<a href="novoUsuario">Cadastrar</a>
<a href="exibirDadosUsuario">Alterar Dados do Usuário</a>
<a href="listarUsuario">Listar Usuários</a>
<a href="exibirBuscarUsuario">Buscar Usuário</a>
<a href="novaCategoria">Inserir Categoria</a>
<a href="listarCategoria">Listar Categoria</a>
<a href="novoTopico">Criar Tópico</a>
<a href="listarTopico">Listar Topico</a>
<a href="novoPost">Criar Post</a>
<a href="listarPost">Listar Post</a>
<a href="exibirLogin" >Fazer Login</a>
<a href="logout">Logout</a>
